### ISSUE TITLE
Task 2: Modularity with AngularJS

### ISSUE THREAD

**Issue by hemangsk** [coala/landing#19]
The idea is to have separate file for each tab.
The index.html should have minimal code related to tab.
The addition of new tabs should be as simple as creating a new html file and adding a line in index.html.

Todos

- [x] Separate out tabs by adding TabController

- [ ]  Separate controllers for each tab in their files

- [x]  Bower for general FE dependency management

**Comment by meetmangukiya** [comment]
Angular 2 ?

**Comment by hemangsk** [comment]
Angular v1 @meetmangukiya
