### ISSUE TITLE
Seperate CSS in vendor and customization

### ISSUE THREAD

**Issue by sils** [coala/landing#2]
E.g. the material CSS should be in an own file, we shouldn't need a style.css of that size.

**Comment by hemangsk** [comment]
Added materializecss, jquery in a `vendors` folder
https://github.com/hemangsk/coala-web-dev/tree/master/vendors

And custom css files  are now in here
https://github.com/hemangsk/coala-web-dev/tree/master/resources/css

**Comment by sils** [comment]
Nice, FWIW I don't care if we have it in a vendor directory or we just pull it in from a CDN. I'm not so sure the CSS files belong in the repo though.
