### ISSUE TITLE
Task 4: Showing details of a bear 

### ISSUE THREAD

**Issue by hemangsk** [coala/landing#26]
Once the user clicks the bear card, they should be shown details of that bear.
This can be done by implementing a "Theatre Effect" (FB used this name for a similar effect ), once the user click a bear, a theatre gets set up and all the details of that bear are displayed.

Todos
- [x]  Implement a coala style theatre effect 🚀  

- [ ]  Gather all the scattered CSS and compile it into a 'one nice file' 😃

**Comment by hemangsk** [comment]
Bear Details view screenshots from local machine,

![screen shot 2016-12-17 at 7 54 18 pm](https://cloud.githubusercontent.com/assets/13018570/21287500/dd70e974-c492-11e6-8e49-dbb31d0cee97.png)
![screen shot 2016-12-17 at 7 53 43 pm](https://cloud.githubusercontent.com/assets/13018570/21287502/fca11b20-c492-11e6-9a7f-194f2ec49db9.png)
![screen shot 2016-12-17 at 7 37 28 pm](https://cloud.githubusercontent.com/assets/13018570/21287503/ffdf342a-c492-11e6-95c6-e3d7fa85a053.png)

**Comment by Makman2** [comment]
Insane, looks super cool :D
